# Generated by Django 5.0.3 on 2024-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(default=0, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(max_length=255)),
                ('genres', models.JSONField()),
            ],
        ),
    ]
