# Generated by Django 5.0.3 on 2024-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_movie_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchMoviesState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('max_page', models.IntegerField(default=10)),
            ],
        ),
    ]
